version: 2.1
orbs:
    node: circleci/node@x.y 
workflows:
  build:
    jobs:
      test:
        docker:
       - image: cimg/node:<node-version>
      steps:
       - checkout
       - node/install-packages
