orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn
      - run: yarn prettier
      - run: yarn lint
      - run: yarn build
 

workflows:
  node-tests:
    jobs:
      - build
      