orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install:
          install-yarn: true
      - run: pwd
      - run: ls
      - run: git add
      - run: git remote add origin https://github.com/RafaelPena31/frame-wallet.git
      - run: git pull origin master
      - run: ls
      - run: yarn 
      - run: ls
      - run: yarn lint
      - run: yarn prettier
      - run: yarn build
 

workflows:
  node-tests:
    jobs:
      - build
      


