orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run:
          name: WEB - Install dependency's
          command: cd web && yarn
      - run:
          name: WEB - Prettier (Code Styling)
          command: cd web && yarn prettier
      - run:
          name: WEB - ESlint (Code lint)
          command: cd web && yarn lint
      - run:
          name: WEB - Application - Build
          command: cd web && yarn build
      - run:
          name: MOBILE - Install dependency's
          command: cd mobile && yarn
      - run:
          name: MOBILE - ESlint (Code lint)
          command: cd mobile && yarn lint

workflows:
  node-tests:
    jobs:
      - build
