version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:latest
  machine-executor:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  build:
    executor: docker-executor
    working_directory: ~/frame-wallet.
    steps:
      - run: ls
      - run: npm install yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn prettier
      - run: build

workflows:
  test_build:
    jobs:
      - build
