orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run:
          name: Install dependecys
          command: yarn
      - run: 
          name: Prettier (Code Styling)
          command: yarn prettier
      - run: 
          name: ESlint (Code lint)
          command: yarn lint
      - run: 
          name: Application - Build 
          command: yarn build

workflows:
  node-tests:
    jobs:
      - build
