name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: WEB - Install dependence's
        run: cd web && yarn

      - name: WEB - Check prettier
        run: yarn prettier

      - name: WEB - Check lint
        run: yarn lint

      - name: WEB - Check build
        run: yarn build

      - name: MOBILE - Install dependence's
        run: cd ../mobile && yarn

      - name: MOBILE - Check lint
        run: yarn lint
